Make the max/min text a little bigger in the Numeric Component
mxtommy/Kip pull request #362
Opened 2024-04-02 23:44 UTC by mshulman

Instead of setting the max height to 0.075 of the canvas, set it to 0.13 of the canvas. 

This looks a little bigger, and still resizes appropriately.

2024-04-03 18:14 UTC, mshulman commented
Suggestions to the help text  for Configuration Management

2024-04-05 04:37 UTC, godind requested changes

2024-04-05 04:37 UTC, godind commented on src/app/widgets/widget-numeric/widget-numeric.component.ts
> +    const maxTextHeight = Math.floor(this.canvasMM.nativeElement.height * 0.13);
It starts big, but goes small again on first data refresh. This is probably not the right place, or the max size looping bellow is not taking into account.

2024-04-05 04:41 UTC, godind commented on src/app/widgets/widget-numeric/widget-numeric.component.ts
> +    const maxTextHeight = Math.floor(this.canvasMM.nativeElement.height * 0.13);
I could have approved the other changes. Try to create PRs that are targeted to one area or feature set. Next time ;)

2024-04-05 15:07 UTC, mshulman commented
It looked good on my setup when I tested.

I really need to learn how Angular Canvases work.

-ms

On Thu, Apr 4, 2024, 9:41 PM David G ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/app/widgets/widget-numeric/widget-numeric.component.ts
> <https://github.com/mxtommy/Kip/pull/362#discussion_r1552873200>:
>
> > @@ -320,7 +320,7 @@ export class WidgetNumericComponent extends BaseWidgetComponent implements OnIni
>
>      let valueText: string = '';
>      const maxTextWidth = Math.floor(this.canvasMM.nativeElement.width * 0.45);
> -    const maxTextHeight = Math.floor(this.canvasMM.nativeElement.height * 0.075);
> +    const maxTextHeight = Math.floor(this.canvasMM.nativeElement.height * 0.13);
>
> I could have approved the other changes. Try to create PRs that are
> targeted to one area or feature set. Next time ;)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mxtommy/Kip/pull/362#discussion_r1552873200>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALKNBDLIABHSEQJQU3N3UTY3YTQ7AVCNFSM6AAAAABFUIXAIGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOBRHA2DGNRVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-05 15:28 UTC, godind commented
No worries. That's what PR reviews are for. But they do take time!

2024-04-05 20:51 UTC, mshulman commented
Reverted the maxHeight change.

2024-04-05 22:15 UTC, merged